import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
def first_part():
    df = pd.read_csv(r"D:\ML-Course\05-Seaborn\dm_office_sales.csv")
    print(df.head())
    plt.figure(figsize=(12,4), dpi=200)
    #sns.scatterplot(data=df, x = "salary", y = "sales", size = "work experience", style="level of education")
    sns.scatterplot(data=df, x = "salary", y = "sales", hue = "level of education", style="level of education")
    ##sns.scatterplot(data=df, x = "sales", y = "salary")
    plt.savefig("seaborn1.png")
    plt.show()
def second_part():
    df = pd.read_csv(r"D:\ML-Course\05-Seaborn\dm_office_sales.csv")
    print(df.head())
    ##sns.rugplot(data=df, x="salary")
    sns.set_style("darkgrid")
    sns.displot(data=df, x="salary", bins=100, color = "orange", kde=True)
    plt.show()
def third_part():
    df = pd.read_csv(r"D:\ML-Course\05-Seaborn\dm_office_sales.csv")
    print(df.head())
    print(df["division"].value_counts())
    plt.figure(figsize=(10,4), dpi=200)
    ##plt.ylim(90,260)
    ##sns.countplot(data=df, x="division")
    ##sns.countplot(data=df,x="level of education",hue="division", palette="Set2")
    sns.barplot(data=df, x = "level of education", y = "salary", estimator=np.mean, errorbar="sd", hue="division")
    plt.show()
def fourth_part():
    df = pd.read_csv(r"D:\ML-Course\05-Seaborn\StudentsPerformance.csv")
    pd.set_option("display.width", None)
    print(df.head())
    plt.figure(figsize=(10,4), dpi=200)
    ##sns.boxplot(data=df, y="reading score", x = "parental level of education", hue="test preparation course")
    ##sns.violinplot(data=df, y="reading score", x = "parental level of education", hue="test preparation course")
    sns.swarmplot(data=df,x="math score", y="gender", hue="test preparation course", dodge=True)
    plt.show()
def fifth_part():
    df = pd.read_csv(r"D:\ML-Course\05-Seaborn\StudentsPerformance.csv")
    print(df.head())
    ##sns.jointplot(data=df, x="math score", y="reading score")
    ##sns.jointplot(data=df, x="math score", y="reading score", kind = "hex")
    ##sns.jointplot(data=df, x="math score", y="reading score", kind = "hist")
    ##sns.jointplot(data=df, x="math score", y="reading score", hue="gender")
    ##sns.pairplot(data=df, hue="gender", diag_kind="hist")
    sns.catplot(data=df, x="gender",y="math score", kind="box", row="lunch", col="test preparation course")
    pair_grid = sns.PairGrid(data=df, hue="gender")
    pair_grid.add_legend()
    pair_grid = pair_grid.map_upper(sns.scatterplot)
    pair_grip = pair_grid.map_lower(sns.kdeplot)
    pair_grip = pair_grid.map_diag(sns.kdeplot)
    plt.show()

df = pd.read_csv(r"D:\ML-Course\05-Seaborn\country_table.csv")
pd.set_option("display.width", None)
print(df.head())
df.set_index("Countries", inplace=True)
print(df.head())
plt.figure(figsize=(12,8), dpi=200)
##sns.heatmap(data=df.drop("Life expectancy", axis = 1), annot=True)
sns.clustermap(data=df.drop("Life expectancy", axis = 1), annot=True)
plt.show()